development:
  adapter: postgresql
  encoding: utf8
  database: bartcrm-dev
  pool: 5
  host: localhost
  username: postgres
  password: blacmar1!

test:
  adapter: postgresql
  encoding: SQL_ASCII
  database: bartcrm-test
  pool: 5
  host: localhost
  username: postgres
  password: blacmar1!

production:
  adapter: postgresql
  encoding: unicode
  database: bartcrm-prod
  pool: 5
  host: localhost
  username: action
  password: 
