development:
  adapter: postgresql
  encoding: unicode
  database: bartcrm-dev
  pool: 5
  host: localhost
  username: action
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: bartcrm-test
  pool: 5
  host: localhost
  username: action
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: bartcrm-prod
  pool: 5
  host: localhost
  username: action
  password: 
