development:
  adapter: postgresql
  encoding: unicode
  database: bartcrm-dev
  pool: 5
  host: localhost
  username: brateq
  password: blacmar1!

test:
  adapter: postgresql
  encoding: unicode
  database: bartcrm-test
  pool: 5
  host: localhost
  username: brateq
  password: blacmar1!

production:
  adapter: postgresql
  encoding: unicode
  database: bartcrm-prod
  pool: 5
  host: localhost
  username: brateq
  password: blacmar1!
